import {
  BriefcaseBusiness,
  GraduationCap,
  Library,
  UserRoundPlus,
} from "lucide-react";

export const staffConfigs = {
  teacher: {
    title: "Create Teacher",
    editTitle: "Edit Teacher",
    description: "Add and manage teaching staff information.",
    employmentTitle: "Employment Details",
    icon: GraduationCap,
    iconBg: "bg-indigo-100",
    iconColor: "text-indigo-600",

    fields: [
      {
        name: "firstName",
        label: "First Name",
        type: "text",
        placeholder: "Enter first name",
        required: true,
        section: "personal",
      },
      {
        name: "lastName",
        label: "Last Name",
        type: "text",
        placeholder: "Enter last name",
        required: true,
        section: "personal",
      },
      {
        name: "email",
        label: "Email",
        type: "email",
        placeholder: "teacher@example.com",
        required: true,
        section: "personal",
      },
      {
        name: "phone",
        label: "Phone",
        type: "tel",
        placeholder: "Enter phone number",
        required: true,
        section: "personal",
      },
      {
        name: "password",
        label: "Temporary Password",
        type: "password",
        placeholder: "Create temporary password",
        minLength: 6,
        section: "personal",
      },
      {
        name: "gender",
        label: "Gender",
        type: "select",
        options: ["Male", "Female", "Other"],
        required: true,
        section: "personal",
      },
      {
        name: "dateOfBirth",
        label: "Date of Birth",
        type: "date",
        required: true,
        section: "personal",
      },
      {
        name: "qualification",
        label: "Qualification",
        type: "text",
        placeholder: "e.g. M.Sc, B.Ed",
        required: true,
        section: "employment",
      },
      {
        name: "specialization",
        label: "Specialization",
        type: "text",
        placeholder: "e.g. Mathematics",
        required: true,
        section: "employment",
      },
      {
        name: "experience",
        label: "Experience",
        type: "text",
        placeholder: "e.g. 5 Years",
        section: "employment",
      },
      {
        name: "joiningDate",
        label: "Joining Date",
        type: "date",
        required: true,
        section: "employment",
      },
      {
        name: "employeeId",
        label: "Employee ID",
        type: "text",
        placeholder: "e.g. TCH-001",
        required: true,
        section: "employment",
      },
      {
        name: "department",
        label: "Department",
        type: "text",
        placeholder: "e.g. Science",
        section: "employment",
      },
      {
        name: "address",
        label: "Address",
        type: "textarea",
        placeholder: "Enter complete address",
        section: "personal",
        fullWidth: true,
      },
    ],
  },

  peon: {
    title: "Create Peon Staff",
    editTitle: "Edit Peon Staff",
    description: "Add and manage school support staff.",
    employmentTitle: "Employment Details",
    icon: BriefcaseBusiness,
    iconBg: "bg-amber-100",
    iconColor: "text-amber-600",

    fields: [
      {
        name: "firstName",
        label: "First Name",
        type: "text",
        placeholder: "Enter first name",
        required: true,
        section: "personal",
      },
      {
        name: "lastName",
        label: "Last Name",
        type: "text",
        placeholder: "Enter last name",
        required: true,
        section: "personal",
      },
      {
        name: "email",
        label: "Email",
        type: "email",
        placeholder: "staff@example.com",
        section: "personal",
      },
      {
        name: "phone",
        label: "Phone",
        type: "tel",
        placeholder: "Enter phone number",
        required: true,
        section: "personal",
      },
      {
        name: "password",
        label: "Temporary Password",
        type: "password",
        placeholder: "Create temporary password",
        minLength: 6,
        section: "personal",
      },
      {
        name: "gender",
        label: "Gender",
        type: "select",
        options: ["Male", "Female", "Other"],
        required: true,
        section: "personal",
      },
      {
        name: "dateOfBirth",
        label: "Date of Birth",
        type: "date",
        section: "personal",
      },
      {
        name: "joiningDate",
        label: "Joining Date",
        type: "date",
        required: true,
        section: "employment",
      },
      {
        name: "employeeId",
        label: "Employee ID",
        type: "text",
        placeholder: "e.g. PON-001",
        required: true,
        section: "employment",
      },
      {
        name: "shift",
        label: "Shift",
        type: "select",
        options: ["Morning", "Afternoon", "Full Day"],
        required: true,
        section: "employment",
      },
      {
        name: "emergencyContact",
        label: "Emergency Contact",
        type: "tel",
        placeholder: "Enter emergency contact",
        section: "personal",
      },
      {
        name: "address",
        label: "Address",
        type: "textarea",
        placeholder: "Enter complete address",
        required: true,
        section: "personal",
        fullWidth: true,
      },
    ],
  },

  library: {
    title: "Create Library Staff",
    editTitle: "Edit Library Staff",
    description: "Add and manage library staff information.",
    employmentTitle: "Library & Employment Details",
    icon: Library,
    iconBg: "bg-emerald-100",
    iconColor: "text-emerald-600",

    fields: [
      {
        name: "firstName",
        label: "First Name",
        type: "text",
        placeholder: "Enter first name",
        required: true,
        section: "personal",
      },
      {
        name: "lastName",
        label: "Last Name",
        type: "text",
        placeholder: "Enter last name",
        required: true,
        section: "personal",
      },
      {
        name: "email",
        label: "Email",
        type: "email",
        placeholder: "librarian@example.com",
        required: true,
        section: "personal",
      },
      {
        name: "phone",
        label: "Phone",
        type: "tel",
        placeholder: "Enter phone number",
        required: true,
        section: "personal",
      },
      {
        name: "password",
        label: "Temporary Password",
        type: "password",
        placeholder: "Create temporary password",
        minLength: 6,
        section: "personal",
      },
      {
        name: "gender",
        label: "Gender",
        type: "select",
        options: ["Male", "Female", "Other"],
        required: true,
        section: "personal",
      },
      {
        name: "dateOfBirth",
        label: "Date of Birth",
        type: "date",
        section: "personal",
      },
      {
        name: "joiningDate",
        label: "Joining Date",
        type: "date",
        required: true,
        section: "employment",
      },
      {
        name: "employeeId",
        label: "Employee ID",
        type: "text",
        placeholder: "e.g. LIB-001",
        required: true,
        section: "employment",
      },
      {
        name: "libraryRole",
        label: "Library Role",
        type: "text",
        placeholder: "e.g. Librarian",
        required: true,
        section: "employment",
      },
      {
        name: "qualification",
        label: "Qualification",
        type: "text",
        placeholder: "e.g. M.Lib",
        required: true,
        section: "employment",
      },
      {
        name: "experience",
        label: "Experience",
        type: "text",
        placeholder: "e.g. 5 Years",
        section: "employment",
      },
      {
        name: "address",
        label: "Address",
        type: "textarea",
        placeholder: "Enter complete address",
        section: "personal",
        fullWidth: true,
      },
    ],
  },
};
